# Generated by Django 4.2.4 on 2023-10-13 18:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="registrousuario",
            old_name="password",
            new_name="contrasena",
        ),
        migrations.RenameField(
            model_name="registrousuario",
            old_name="user",
            new_name="usuario",
        ),
    ]
