# Generated by Django 4.2.4 on 2023-10-17 05:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_rename_password_registrousuario_contrasena_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="productos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("slug", models.SlugField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="productos"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("prenda superior", "Prenda Superior"),
                            ("prenda inferior", "Prenda Inferior"),
                            ("zapatillas", "Zapatillas"),
                            ("laptops", "Laptops"),
                            ("celulares", "Celulares"),
                            ("audifonos", "Audifonos"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Producto",
                "verbose_name_plural": "Productos",
                "ordering": ["name"],
            },
        ),
    ]
