# Generated by Django 4.2.4 on 2023-10-17 12:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_categoria_alter_productos_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="categoria",
            old_name="nombre",
            new_name="name",
        ),
    ]
